export const RECIPROCAL_TYPES: Record<string, string | null> = {
  PARENT: "CHILD",
  CHILD: "PARENT",
  SPOUSE: "SPOUSE",
  PARTNER: "PARTNER",
  EX_SPOUSE: "EX_SPOUSE",
  SIBLING: "SIBLING",
  HALF_SIBLING: "HALF_SIBLING",
  STEP_SIBLING: "STEP_SIBLING",
  GRANDPARENT: "GRANDCHILD",
  GRANDCHILD: "GRANDPARENT",
  AUNT_UNCLE: "NIECE_NEPHEW",
  NIECE_NEPHEW: "AUNT_UNCLE",
  COUSIN: "COUSIN",
  STEP_PARENT: "STEP_CHILD",
  STEP_CHILD: "STEP_PARENT",
  ADOPTIVE_PARENT: "ADOPTIVE_CHILD",
  ADOPTIVE_CHILD: "ADOPTIVE_PARENT",
  FAMILY_FRIEND: "FAMILY_FRIEND",
  // No automatic reciprocal for these roles
  CAREGIVER: null,
  GUARDIAN: null
};

