export const RECIPROCAL_TYPES: Record<string, string | null> = {
  PARENT:       "CHILD",
  CHILD:        "PARENT",
  SPOUSE:       "SPOUSE",
  PARTNER:      "PARTNER",
  SIBLING:      "SIBLING",
  GRANDPARENT:  "GRANDCHILD",
  GRANDCHILD:   "GRANDPARENT",
  AUNT_UNCLE:   "NIECE_NEPHEW",
  NIECE_NEPHEW: "AUNT_UNCLE",
  COUSIN:       "COUSIN",
  GUARDIAN:     "WARD",
  WARD:         "GUARDIAN",
  FRIEND:       "FRIEND",
  CAREGIVER:    null,
};
